services:
  llama-city:
    build:
      context: ./llama-city
    networks:
      - app-network
    ports:
      - "8080:8080"
      - "50051:50051"

  datagram-intelligence:
    build:
      context: ./datagram-intelligence
    networks:
      - app-network
    ports:
      - "3000:3000"
      - "50052:50052"
    depends_on:
      - llama-city

  llama-citizen:
    build:
      context: ./llama-citizen
    depends_on:
      - llama-city
    networks:
      - app-network
    ports:
      - "11434:11434"
    restart: always

networks:
  app-network:
    driver: bridge
